# fly.toml app configuration file generated for team-chatbot-backend on 2025-05-29T22:16:42Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'team-chatbot-backend'
primary_region = 'otp'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']
  protocol = "tcp"
  [http_service.upgrades]
    websocket = true

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
